# Generated by Django 4.0.5 on 2022-06-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='name',
        ),
        migrations.CreateModel(
            name='history_winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_vote.hotel')),
            ],
        ),
    ]
