# Generated by Django 4.0.5 on 2022-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_vote', '0004_alter_history_winner_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_winner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
