# Generated by Django 4.0.5 on 2022-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_vote', '0006_alter_hotel_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_votes',
            field=models.FloatField(max_length=3),
        ),
    ]
