# Generated by Django 4.0.5 on 2022-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_vote', '0007_alter_customuser_max_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_votes',
            field=models.CharField(max_length=3),
        ),
    ]
